//
// Generated file, do not edit! Created by nedtool 4.6 from broadcast.msg.
//

#ifndef _BROADCAST_M_H_
#define _BROADCAST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>broadcast.msg:17</tt> by nedtool.
 * <pre>
 * message BroadcastMsg
 * {
 *     int source;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class BroadcastMsg : public ::cMessage
{
  protected:
    int source_var;
    int hopCount_var;

  private:
    void copy(const BroadcastMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BroadcastMsg&);

  public:
    BroadcastMsg(const char *name=NULL, int kind=0);
    BroadcastMsg(const BroadcastMsg& other);
    virtual ~BroadcastMsg();
    BroadcastMsg& operator=(const BroadcastMsg& other);
    virtual BroadcastMsg *dup() const {return new BroadcastMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doPacking(cCommBuffer *b, BroadcastMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BroadcastMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BROADCAST_M_H_

